package com.gigforce.app.utils

/**
 * @author Rohit Sharma
 * date : 21-07-2020
 */
enum class StringConstants(val value: String) {
    //Assessment Module Constants
    ASSESSMENT_DIALOG_STATE("ASSESS_STATE"),
    CERTIFICATE_SSC("CERTIFICATE_SSC.png"),
    GIGER_ID("GIGER_ID.png"),
    GIG_DETAILS("GIG_DETAILS"),
    ASSESSMENT_PASSED("ASSESSMENT_PASSED"),
    EVENT_STATE_GIG_HISTORY("EVENT_STATE_GIG_HISTORY"),
    PROFILE_ID("PROFILE_ID"),
    IS_WHATSAPP_NUMBER("IS_WHATSAPP_NUMBER"),
    CONTACT_EDIT_STATE("CONTACT_EDIT_STATE"),
    CONTACT_TO_EDIT("CONTACT_TO_EDIT"),
    EMAIL_TO_EDIT("EMAIL_TO_EDIT"),
    IS_REGISTERED_NUMBER("IS_REGISTERED_NUMBER"),
    DURATION("DURATION"),
    ASSESSMENT_NAME("ASSESSMENT_NAME"),
    QUESTIONS_COUNT("QUESTIONS_COUNT"),
    LEVEL("LEVEL"),
    RIGHT_ANSWERS("RIGHT_ANSWERS"),
    ANSWERS_ARR("ANSWERS_ARR"),
    TIME_TAKEN("TIME_TAKEN"),
    INVITE_USER_ID("INVITE_USER_ID"),
    ROLE_ID("ROLE_ID"),
    SKIPPED_ABOUT_INTRO("SKIPPED_ABOUT_INTO"),
    DOC_URL("DOC_URL"),
    SHOW_ACTION_BUTTONS("SHOW_ACTION_BUTTONS"),
    NAV_TO_QUESTIONNARE("NAV_TO_QUESTIONNARE"),
    BACK_PRESSED("BACK_PRESSED"),
    MOVE_TO_NEXT_STEP("MOVE_TO_NEXT_STEP"),
    NAVIGATE_TO_MARK_AS_INTERESTED("NAVIGATE_TO_MARK_AS_INTERESTED")

}