package com.gigforce.app.utils

/**
 * @author Rohit Sharma
 * date : 21-07-2020
 */
enum class StringConstants(val value: String) {
    //Assessment Module Constants
    ASSESSMENT_DIALOG_STATE("ASSESS_STATE"),
    CERTIFICATE_SSC("CERTIFICATE_SSC.png"),
    GIGER_ID("GIGER_ID.png"),
    GIG_DETAILS("GIG_DETAILS"),
    ASSESSMENT_PASSED("ASSESSMENT_PASSED"),
    EVENT_STATE_GIG_HISTORY("EVENT_STATE_GIG_HISTORY"),
    PROFILE_ID("PROFILE_ID"),
    IS_WHATSAPP_NUMBER("IS_WHATSAPP_NUMBER"),
    CONTACT_EDIT_STATE("CONTACT_EDIT_STATE"),
    CONTACT_TO_EDIT("CONTACT_TO_EDIT"),
    EMAIL_TO_EDIT("EMAIL_TO_EDIT"),
    IS_REGISTERED_NUMBER("IS_REGISTERED_NUMBER"),
    DURATION("DURATION"),
    ASSESSMENT_NAME("ASSESSMENT_NAME"),
    QUESTIONS_COUNT("QUESTIONS_COUNT"),
    LEVEL("LEVEL"),
    RIGHT_ANSWERS("RIGHT_ANSWERS"),
    ANSWERS_ARR("ANSWERS_ARR"),
    TIME_TAKEN("TIME_TAKEN"),
    INVITE_USER_ID("INVITE_USER_ID"),
    ROLE_ID("ROLE_ID"),
    SKIPPED_ABOUT_INTRO("SKIPPED_ABOUT_INTO"),
    DOC_URL("DOC_URL"),
    SHOW_ACTION_BUTTONS("SHOW_ACTION_BUTTONS"),
    NAV_TO_QUESTIONNARE("NAV_TO_QUESTIONNARE"),
    BACK_PRESSED("BACK_PRESSED"),
    MOVE_TO_NEXT_STEP("MOVE_TO_NEXT_STEP"),
    NAVIGATE_TO_MARK_AS_INTERESTED("NAVIGATE_TO_MARK_AS_INTERESTED"),
    NAV_TO_ROLE("NAV_TO_ROLE"),
    INVITE_BY_AMBASSADOR("INVITE_BY_AMBASSADOR"),
    AMBASSADOR_LATITUDE("AMBASSADOR_LATITUDE"),
    AMBASSADOR_LONGITUDE("AMBASSADOR_LONGITUDE"),
    ROLE_VIA_DEEPLINK("ROLE_VIA_DEEPLINK"),
    JOB_PROFILE_ID("JOB_PROFILE_ID"),
    SAVED_STATE("SAVED_STATE__"),
    SAVED_STATE_VIDEOS_CLIENT_ACT("SAVED_STATE_VIDEOS_CLIENT_ACT"),
    NEXT_DEP("NEXT_DEP"),
    SELECTED_PARTNER("SELECTED_PARTNER"),
    SELECTED_TIME_SLOT("SELECTED_TIME_SLOT"),
    SELECTED_DATE("SELECTED_DATE"),
    FROM_CLIENT_ACTIVATON("FROM_CLIENT_ACTIVATON"),
    TITLE("TITLE"),
    TYPE("TYPE"),
    ACTION("ACTION"),
    DATA("DATA"),
    REJECTION_TYPE("REJECTION_TYPE"),
    CONTENT("WRONG_ANSWERS"),
    CLIENT_ACTIVATION_VIA_DEEP_LINK("CLIENT_ACTIVATION_VIA_DEEP_LINK"),
    NAV_TO_CLIENT_ACT("NAV_TO_CLIENT_ACT"),
    ILLUSTRATION("REJECTION_ILLUSTRATION"),
    TIME_SLOTS("TIME_SLOTS"),
    ACTION_MAIN("ACTION_MAIN"),
    ACTION_SEC("ACTION_SEC"),
    SUBTITLE("SUBTITLE"),
    MOBILE_NUMBER("MOBILE_NUMBER"),
    REJECTION_ILLUSTRATION("REJECTION_ILLUSTRATION"),
    AMBASSADOR_ID("AMBASSADOR_ID"),
    AMB_APPLICATION_OBJ("AMB_APPLICATION_OBJ"),
    FROM_AMB_REQUIREMENTS("FROM_AMB_REQUIREMENTS"),
    PROFILE_PIC_PRESENT("PROFILE_PIC_PRESENT")




}