// Generated by Dagger (https://dagger.dev).
package com.gigforce.common_ui.repository.repo;

import dagger.internal.Factory;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class LearningDataRepository_Factory implements Factory<LearningDataRepository> {
  @Override
  public LearningDataRepository get() {
    return newInstance();
  }

  public static LearningDataRepository_Factory create() {
    return InstanceHolder.INSTANCE;
  }

  public static LearningDataRepository newInstance() {
    return new LearningDataRepository();
  }

  private static final class InstanceHolder {
    private static final LearningDataRepository_Factory INSTANCE = new LearningDataRepository_Factory();
  }
}
