// Generated by Dagger (https://dagger.dev).
package com.gigforce.landing_screen.landingscreen;

import com.gigforce.core.IEventTracker;
import dagger.MembersInjector;
import dagger.internal.InjectedFieldSignature;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class LandingScreenFragment_MembersInjector implements MembersInjector<LandingScreenFragment> {
  private final Provider<IEventTracker> eventTrackerProvider;

  public LandingScreenFragment_MembersInjector(Provider<IEventTracker> eventTrackerProvider) {
    this.eventTrackerProvider = eventTrackerProvider;
  }

  public static MembersInjector<LandingScreenFragment> create(
      Provider<IEventTracker> eventTrackerProvider) {
    return new LandingScreenFragment_MembersInjector(eventTrackerProvider);
  }

  @Override
  public void injectMembers(LandingScreenFragment instance) {
    injectEventTracker(instance, eventTrackerProvider.get());
  }

  @InjectedFieldSignature("com.gigforce.landing_screen.landingscreen.LandingScreenFragment.eventTracker")
  public static void injectEventTracker(LandingScreenFragment instance,
      IEventTracker eventTracker) {
    instance.eventTracker = eventTracker;
  }
}
